### PR TITLE
#4 - Styling improvements for session modal

### PR DESCRIPTION
**Pull request by adarsharyan002**
PR for #3 and #4

### CODE REVIEW

**Comment by nafees87n** [comment]
@adarsharyan002 Can you please post some screenshots of the UI after the changes

**Comment by adarsharyan002** [comment]
Screenshot (619)

**Comment by nafees87n** [comment]
Some suggestions:
- Move the close button to the upper left corner
   - Make it a cross icon
   - Can use react-icons library for it
- Add a heading in the upper part "Session Details"

**Comment by adarsharyan002** [comment]
sure sir,will work on these suggestions
Screenshot (621)

**Comment by aaryak-shah** [comment]
Hi @adarsharyan002 This is already looking great! I want to suggest just 2 more changes to this.
1. The cross button can be inside the blue 'Session Details' header on the right side.
2. The 'Join' button can have the same height as it's corresponding input box.

**Comment by adarsharyan002** [comment]
Thank you for your suggestions sir!

**Comment by adarsharyan002** [comment]
Thank you for your suggestions sir
Screenshot (622)

**Comment by adarsharyan002** [comment]
@nafees87 issues fixed

**Review by nafees87n — APPROVED** [review]

**Pull request merged**
